assets:
	find . ! -name '.*' ! -name '*.css' ! -name '*.js' ! -name '*.png' ! -name '*.jpg' ! -name 'Makefile' ! -name '*.txt' ! -name '*.json' -type f -print0 | xargs -0 sed -i '' -e 's/href="\/css/href="\/2019\/css/g'
	find . ! -name '.*' ! -name '*.css' ! -name '*.js' ! -name '*.png' ! -name '*.jpg' ! -name 'Makefile' ! -name '*.txt' ! -name '*.json' -type f -print0 | xargs -0 sed -i '' -e 's/href="\/public/href="\/2019\/public/g'
	find . ! -name '.*' ! -name '*.css' ! -name '*.js' ! -name '*.png' ! -name '*.jpg' ! -name 'Makefile' ! -name '*.txt' ! -name '*.json' -type f -print0 | xargs -0 sed -i '' -e 's/href="\/images/href="\/2019\/images/g'
	find . ! -name '.*' ! -name '*.css' ! -name '*.js' ! -name '*.png' ! -name '*.jpg' ! -name 'Makefile' ! -name '*.txt' ! -name '*.json' -type f -print0 | xargs -0 sed -i '' -e 's/src="\/images/src="\/2019\/images/g'
	find . ! -name '.*' ! -name '*.css' ! -name '*.js' ! -name '*.png' ! -name '*.jpg' ! -name 'Makefile' ! -name '*.txt' ! -name '*.json' -type f -print0 | xargs -0 sed -i '' -e 's/src="\/js/src="\/2019\/js/g'
	find . ! -name '.*' ! -name '*.css' ! -name '*.js' ! -name '*.png' ! -name '*.jpg' ! -name 'Makefile' ! -name '*.txt' ! -name '*.json' -type f -print0 | xargs -0 sed -i '' -e 's/href="\/lt/href="\/2019\/lt/g'
	find . ! -name '.*' ! -name '*.css' ! -name '*.js' ! -name '*.png' ! -name '*.jpg' ! -name 'Makefile' ! -name '*.txt' ! -name '*.json' -type f -print0 | xargs -0 sed -i '' -e 's/href="\/en/href="\/2019\/en/g'
	find . -name '*.css' -type f -print0 | xargs -0 sed -i '' -e 's/url(\/images\//url(\/2019\/images\//g'
